image: 
  file: .gitpod.Dockerfile

tasks:
  - init: flutter pub get 

# ports:
#   - port: 8080
#     onOpen: open-browser
#     visibility: public

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - eamodio.gitlens
