image: 
  file: .gitpod.Dockerfile

tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - eamodio.gitlens
